spring.application.name=SmartAgroMarket

spring.datasource.url=jdbc:mysql://localhost:3306/agro
spring.datasource.username=root
spring.datasource.password=8270320054
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
